version: 0.2

env:
  variables:
    REACT_APP_API: "testing"
  parameter-store:
    VITE_SHAZAM_CORE_RAPID_API_KEY: "/spotify/geo-api-key"
    VITE_GEO_API_KEY: "/spotify/shazam-core-api-key"
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EA6AXB0IDMOQZ --path /\*
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/