version: 0.2


phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EA6AXB0IDMOQZ --path /\*
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/